### ISSUE TITLE
Why is this?

### ISSUE THREAD

**Issue by BadCat999** [BigBoiCJ/SteamAutoCracker#14]
An error occurred while trying to crack Rogue Legacy 2 (App ID 1253920)
——————
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 411, in connect
  File "urllib3\util\ssl_.py", line 428, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 472, in _ssl_wrap_socket_impl
  File "ssl.py", line 501, in wrap_socket
  File "ssl.py", line 1041, in _create
  File "ssl.py", line 1310, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 573, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='store.steampowered.com', port=443): Max retries exceeded with url: /api/appdetails?appids=1253920&filters=basic (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "steam_auto_cracker.py", line 380, in <module>
  File "steam_auto_cracker.py", line 137, in RetrieveGame
  File "steam_auto_cracker.py", line 28, in __init__
  File "steam_auto_cracker.py", line 32, in DoRequest
  File "requests\api.py", line 76, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='store.steampowered.com', port=443): Max retries exceeded with url: /api/appdetails?appids=1253920&filters=basic (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

**Comment by BigBoiCJ** [comment]
Seems like Python and the request module failed to retrieve your SSL certificates, and thus was unable to create a secure (https) connection to the Steam web page

What OS are you running?

**Comment by BadCat999** [comment]
Windows 11
Okay, maybe it's my problem. Let me think

**Comment by BadCat999** [comment]
Reinstall python 3.10.6 amd64.exe and the problem is resolved.
Has been successfully cracked. Very easy to use tool, thank you

**Comment by BigBoiCJ** [comment]
I'm glad that you managed to fix your problem :)
