### ISSUE TITLE
SSL Error for raw.githubusercontent.com

### ISSUE THREAD

**Issue by pandal34r** [BigBoiCJ/SteamAutoCracker#71]
SteamAutoCracker GUI v2.1.0
---
A Tkinter Python error occurred!
Please report it on GitHub or cs.rin.ru
Make sure to blank any personal detail.
NOTE: '_tkinter.TclError: invalid command name' errors are normal if you closed the window while SAC was busy. In that case, you should not report the issue and just ignore it.
---

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 411, in connect
  File "urllib3\util\ssl_.py", line 428, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 472, in _ssl_wrap_socket_impl
  File "ssl.py", line 501, in wrap_socket
  File "ssl.py", line 1041, in _create
  File "ssl.py", line 1310, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 573, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /BigBoiCJ/SteamAutoCracker/autoupdater/latestversion.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "steam_auto_cracker_gui.py", line 853, in CheckUpdates
  File "steam_auto_cracker_gui.py", line 58, in __init__
  File "steam_auto_cracker_gui.py", line 62, in DoRequest
  File "requests\api.py", line 76, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /BigBoiCJ/SteamAutoCracker/autoupdater/latestversion.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

**Comment by NovaNinja969** [comment]
> Hi! Thanks for the report
> 
> Do you have custom SSL certificates installed by any chance? Or are you maybe using some sort of proxy or VPN?
> 
> It seems like Python failed to retrieve raw.githubusercontent.com's certificate, which shouldn't happen as the website isn't new and is properly certified.
> 
> I don't really know what I can do to bypass this error, except ignoring and using an unsafe connection, which I'm not a fan of. Are you on windows? Are you in a country where github is blocked?

Hello 
yes am on windows and also have a vpn + proxy 
but github is not baned in my country?

thanks anyway

**Comment by wwxiaoqi** [comment]
This seems to be a problem caused by the inability to access raw.githubusercontent.com normally. Could it be an issue with the raw.githubusercontent.com SSL certificate due to VPN usage? Have you tried operating with a proxy?

```
# Windows
set http_proxy=http://127.0.0.1:10809
set https_proxy=http://127.0.0.1:10809

or

# Linux / macOS
export http_proxy=http://127.0.0.1:10809
export https_proxy=http://127.0.0.1:10809
```

Or modify the hosts file?

```
185.199.109.133   raw.githubusercontent.com
```

**Comment by BigBoiCJ** [comment]
> vpn + proxy

Both? Couldn't that cause connection problems?

Anyways, I don't really know how to fix that, and don't have enough knowledge to help you, sorry. The issue probably isn't on SAC's end.

I don't know about @wwxiaoqi 's solution, sorry, not enough knowledge on this
